# theme="catppuccin-mocha"
# theme="default"
# theme="catppuccin-mocha"
# theme="catppuccin-latte"
# theme="catppuccin-frappe"
# theme="catppuccin-macchiato"
theme="dracula"
# theme="tokyo-night"
# theme="gruvbox-dark"
# theme="nord"
